### ISSUE TITLE
[AI Refactor] GitHub Actions concurrency設定追加 - CI効率化

### ISSUE THREAD

**Issue by yn1323** [yn1323/online-draft#111]
## 概要
GitHub Actions concurrency設定を追加してCI効率化を実現

## 現在の問題点
- 新しいコミット時に旧CI実行が継続してリソース浪費
- 最新コミットの結果取得が遅延する
- GitHub Actions使用量が無駄になっている
- 複数CIの同時実行による競合状態

## 対象ファイル
- .github/workflows/storybook-test.yml
- .github/workflows/vrt-compare.yml
- .github/workflows/vrt-deploy.yml  
- .github/workflows/vrt-main.yml
- .github/workflows/vrt-prepare.yml
- .github/workflows/e2e.yml

## 追加コード
```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
```

## 優先度
🟠 中 (計画的)

## 期待効果
- 新コミット時に現在のCI自動キャンセル
- CI実行時間短縮・リソース節約  
- GitHub Actions使用量最適化
- 開発フィードバック速度向上

## 追加情報
配置場所: 各ワークフローの on: セクション直後
技術制約: GitHub Actions concurrency機能使用

**@claude** このリファクタリングを実施してください。
